/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hastaneotomasyonu.doktor;

import com.hastaneotomasyonu.danisma.DanismaIslemleri;
import com.hastaneotomasyonu.danisma.Randevu;
import com.hastaneotomasyonu.veritabani.VeritabaniIslemleri;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USER
 */
public class DoktorEkrani extends javax.swing.JFrame {
     VeritabaniIslemleri veritabaniIslemleri = new VeritabaniIslemleri();
     DanismaIslemleri danismaIslemleri = new DanismaIslemleri();
     DoktorIslemleri doktorIslemleri = new DoktorIslemleri();
    /**
     * Creates new form DoktorDetayEkrani
     */
    DefaultTableModel model;
    public DoktorEkrani() {
        initComponents();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        this.setLocation(x, y);
         model = (DefaultTableModel) RandevuTablosu.getModel();
        randevuGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AltPanel = new javax.swing.JPanel();
        UstPanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        EkranAdi = new javax.swing.JLabel();
        KapamaTusu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RandevuTablosu = new javax.swing.JTable();
        RandevuYazisi = new javax.swing.JLabel();
        AramaYazisi = new javax.swing.JLabel();
        AramaCubugu = new javax.swing.JTextField();
        DurumDeğiştirmeAlani = new javax.swing.JTextField();
        DurumYazisi = new javax.swing.JLabel();
        DegistirTusu = new javax.swing.JButton();
        HstEkranTusu = new javax.swing.JButton();
        SncEkranTusu = new javax.swing.JButton();
        TcYazisi = new javax.swing.JLabel();
        TcAlani = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AdAlani = new javax.swing.JTextField();
        SoyadAlani = new javax.swing.JTextField();
        BransAlani = new javax.swing.JTextField();
        DoktorAlani = new javax.swing.JTextField();
        TarihAlani = new javax.swing.JTextField();
        SaatAlani = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AltPanel.setBackground(new java.awt.Color(0, 0, 153));

        UstPanel.setBackground(new java.awt.Color(0, 102, 204));

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\HastaneOtomasyonu\\src\\com\\hastaneotomasyonu\\images\\icons8-hospital-3-64.png")); // NOI18N

        EkranAdi.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        EkranAdi.setForeground(new java.awt.Color(153, 255, 255));
        EkranAdi.setText("DOKTOR EKRANI");

        KapamaTusu.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\HastaneOtomasyonu\\src\\com\\hastaneotomasyonu\\images\\icons8-close-32.png")); // NOI18N
        KapamaTusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KapamaTusuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UstPanelLayout = new javax.swing.GroupLayout(UstPanel);
        UstPanel.setLayout(UstPanelLayout);
        UstPanelLayout.setHorizontalGroup(
            UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addComponent(Logo)
                .addGap(36, 36, 36)
                .addComponent(EkranAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KapamaTusu))
        );
        UstPanelLayout.setVerticalGroup(
            UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addComponent(KapamaTusu)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(EkranAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RandevuTablosu.setBackground(new java.awt.Color(0, 102, 204));
        RandevuTablosu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        RandevuTablosu.setForeground(new java.awt.Color(0, 0, 153));
        RandevuTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HASTA TC", "AD SOYAD", "BRANŞ", "DOKTOR", "RANDEVU TARİH", "RANDEVU SAAT", "DURUM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RandevuTablosu.setSelectionBackground(new java.awt.Color(0, 102, 204));
        RandevuTablosu.setSelectionForeground(new java.awt.Color(0, 0, 153));
        RandevuTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RandevuTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(RandevuTablosu);

        RandevuYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        RandevuYazisi.setForeground(new java.awt.Color(153, 255, 255));
        RandevuYazisi.setText("RANDEVULAR:");

        AramaYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        AramaYazisi.setForeground(new java.awt.Color(153, 255, 255));
        AramaYazisi.setText("Randevu Ara:");

        AramaCubugu.setBackground(new java.awt.Color(0, 102, 204));
        AramaCubugu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        AramaCubugu.setForeground(new java.awt.Color(0, 0, 153));
        AramaCubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AramaCubuguKeyReleased(evt);
            }
        });

        DurumDeğiştirmeAlani.setBackground(new java.awt.Color(0, 102, 204));
        DurumDeğiştirmeAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        DurumDeğiştirmeAlani.setForeground(new java.awt.Color(0, 0, 153));

        DurumYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        DurumYazisi.setForeground(new java.awt.Color(153, 255, 255));
        DurumYazisi.setText("DURUM:");

        DegistirTusu.setBackground(new java.awt.Color(0, 102, 204));
        DegistirTusu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        DegistirTusu.setForeground(new java.awt.Color(0, 0, 153));
        DegistirTusu.setText("DEĞİŞTİR");
        DegistirTusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DegistirTusuActionPerformed(evt);
            }
        });

        HstEkranTusu.setBackground(new java.awt.Color(0, 102, 204));
        HstEkranTusu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        HstEkranTusu.setForeground(new java.awt.Color(0, 0, 153));
        HstEkranTusu.setText("Hasta Ekranı");
        HstEkranTusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HstEkranTusuActionPerformed(evt);
            }
        });

        SncEkranTusu.setBackground(new java.awt.Color(0, 102, 204));
        SncEkranTusu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        SncEkranTusu.setForeground(new java.awt.Color(0, 0, 153));
        SncEkranTusu.setText("Sonuç Ekranı");
        SncEkranTusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SncEkranTusuActionPerformed(evt);
            }
        });

        TcYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        TcYazisi.setForeground(new java.awt.Color(153, 255, 255));
        TcYazisi.setText("T.C.");

        TcAlani.setEditable(false);
        TcAlani.setBackground(new java.awt.Color(0, 102, 204));
        TcAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        TcAlani.setForeground(new java.awt.Color(0, 0, 153));
        TcAlani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TcAlaniKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("Ad:");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Soyad:");

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText(" Branş:");

        jLabel4.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("Doktor:");

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("Tarih:");

        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Saat:");

        AdAlani.setEditable(false);
        AdAlani.setBackground(new java.awt.Color(0, 102, 204));
        AdAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        AdAlani.setForeground(new java.awt.Color(0, 0, 153));

        SoyadAlani.setEditable(false);
        SoyadAlani.setBackground(new java.awt.Color(0, 102, 204));
        SoyadAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        SoyadAlani.setForeground(new java.awt.Color(0, 0, 153));

        BransAlani.setEditable(false);
        BransAlani.setBackground(new java.awt.Color(0, 102, 204));
        BransAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        BransAlani.setForeground(new java.awt.Color(0, 0, 153));

        DoktorAlani.setEditable(false);
        DoktorAlani.setBackground(new java.awt.Color(0, 102, 204));
        DoktorAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        DoktorAlani.setForeground(new java.awt.Color(0, 0, 153));

        TarihAlani.setEditable(false);
        TarihAlani.setBackground(new java.awt.Color(0, 102, 204));
        TarihAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        TarihAlani.setForeground(new java.awt.Color(0, 0, 153));

        SaatAlani.setEditable(false);
        SaatAlani.setBackground(new java.awt.Color(0, 102, 204));
        SaatAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        SaatAlani.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout AltPanelLayout = new javax.swing.GroupLayout(AltPanel);
        AltPanel.setLayout(AltPanelLayout);
        AltPanelLayout.setHorizontalGroup(
            AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(AltPanelLayout.createSequentialGroup()
                .addComponent(RandevuYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(AramaYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(AltPanelLayout.createSequentialGroup()
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TcYazisi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DurumYazisi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DurumDeğiştirmeAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(TcAlani)
                    .addComponent(BransAlani))
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AltPanelLayout.createSequentialGroup()
                        .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AltPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AltPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AltPanelLayout.createSequentialGroup()
                                .addComponent(AdAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AltPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TarihAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AltPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SoyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(AltPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(HstEkranTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(SncEkranTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114))
                            .addGroup(AltPanelLayout.createSequentialGroup()
                                .addComponent(DoktorAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(AltPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DegistirTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(AltPanelLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(SaatAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AltPanelLayout.setVerticalGroup(
            AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltPanelLayout.createSequentialGroup()
                .addComponent(UstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RandevuYazisi)
                    .addComponent(AramaYazisi)
                    .addComponent(AramaCubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DurumYazisi)
                    .addComponent(DurumDeğiştirmeAlani, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(DegistirTusu, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TcYazisi)
                        .addComponent(TcAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AdAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SoyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AltPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BransAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DoktorAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TarihAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SaatAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SncEkranTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HstEkranTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(AltPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HstEkranTusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HstEkranTusuActionPerformed
        KayitliHastaEkrani kayitliHastaEkrani = new KayitliHastaEkrani();
        kayitliHastaEkrani.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_HstEkranTusuActionPerformed

    private void KapamaTusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KapamaTusuMouseClicked
        System.exit(0);
    }//GEN-LAST:event_KapamaTusuMouseClicked

    private void SncEkranTusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SncEkranTusuActionPerformed
        TahlilSonucEkrani tahlilSonucEkrani = new TahlilSonucEkrani();
        tahlilSonucEkrani.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_SncEkranTusuActionPerformed

    private void DegistirTusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DegistirTusuActionPerformed

         if (DurumDeğiştirmeAlani.getText().equals("")) {
        } else {
            String tc = TcAlani.getText();
            String durum = DurumDeğiştirmeAlani.getText();
            
            doktorIslemleri.Guncelle(tc, durum);

            randevuGoruntule();
        }
    }//GEN-LAST:event_DegistirTusuActionPerformed
    public void dinamikAra(String ara){
     TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>(model);
        RandevuTablosu.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void AramaCubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AramaCubuguKeyReleased
       String ara = AramaCubugu.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_AramaCubuguKeyReleased

    private void RandevuTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RandevuTablosuMouseClicked
        int selectedRow = RandevuTablosu.getSelectedRow();
        String tc = model.getValueAt(selectedRow, 0).toString();
        TcAlani.setText(tc);        
        String adSoyad = model.getValueAt(selectedRow, 1).toString();
        String[] dizi = adSoyad.split(" ");
        String ad;
        String soyad;
        switch (dizi.length) {
            case 4:
                ad = dizi[0] + " " + dizi[1];
                soyad = dizi[2] + " " + dizi[3];
                break;
            case 3:
                ad = dizi[0] + " " + dizi[1];
                soyad = dizi[2];
                break;
            default:
                ad = dizi[0];
                soyad = dizi[1];
                break;
        }
        AdAlani.setText(ad);
        SoyadAlani.setText(soyad);
       
        String brans = model.getValueAt(selectedRow, 2).toString();
        BransAlani.setText(brans);
        
        String doktor = model.getValueAt(selectedRow, 3).toString();
        DoktorAlani.setText(doktor);
        
        String tarih = model.getValueAt(selectedRow, 4).toString();
        TarihAlani.setText(tarih);
        
        String saat = model.getValueAt(selectedRow, 5).toString();
        SaatAlani.setText(saat);
        
        String durum = model.getValueAt(selectedRow, 6).toString();
        DurumDeğiştirmeAlani.setText(durum);
    }//GEN-LAST:event_RandevuTablosuMouseClicked

    private void TcAlaniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TcAlaniKeyTyped
        char c = evt.getKeyChar();
        if (TcAlani.getText().length() >= 11 || (c == KeyEvent.VK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TcAlaniKeyTyped
     public void randevuGoruntule() {
        model.setRowCount(0);

        ArrayList<Randevu> randevu = new ArrayList<>();

        randevu = danismaIslemleri.randevuGoster();

        if (randevu != null) {
            for (Randevu rand : randevu) {
                int no = rand.getId();
                String tc = rand.getTc();
                String adsoyad = rand.getAd() + " " + rand.getSoyad();
                String brans = rand.getBrans();
                String doktorAdSoyad = rand.getDoktorAdi();
                String tarih = rand.getTarih();
                String durum = rand.getDurum();
                String saat = rand.getSaat();

                Object[] ekleme = {tc, adsoyad, brans, doktorAdSoyad, tarih ,saat ,durum};
                model.addRow(ekleme);

            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoktorEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoktorEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoktorEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoktorEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoktorEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdAlani;
    private javax.swing.JPanel AltPanel;
    private javax.swing.JTextField AramaCubugu;
    private javax.swing.JLabel AramaYazisi;
    private javax.swing.JTextField BransAlani;
    private javax.swing.JButton DegistirTusu;
    private javax.swing.JTextField DoktorAlani;
    private javax.swing.JTextField DurumDeğiştirmeAlani;
    private javax.swing.JLabel DurumYazisi;
    private javax.swing.JLabel EkranAdi;
    private javax.swing.JButton HstEkranTusu;
    private javax.swing.JLabel KapamaTusu;
    private javax.swing.JLabel Logo;
    private javax.swing.JTable RandevuTablosu;
    private javax.swing.JLabel RandevuYazisi;
    private javax.swing.JTextField SaatAlani;
    private javax.swing.JButton SncEkranTusu;
    private javax.swing.JTextField SoyadAlani;
    private javax.swing.JTextField TarihAlani;
    private javax.swing.JTextField TcAlani;
    private javax.swing.JLabel TcYazisi;
    private javax.swing.JPanel UstPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
