/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hastaneotomasyonu.sekreter;

import static com.hastaneotomasyonu.anaIslemler.DoktorEkleme.doktorNo;
import com.hastaneotomasyonu.hasta.Hasta;
import com.hastaneotomasyonu.veritabani.VeritabaniIslemleri;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USER
 */
public class SekreterEkrani extends javax.swing.JFrame {
    VeritabaniIslemleri veritabaniIslemleri = new VeritabaniIslemleri();
    SekreterIslemleri sekreterIslemleri = new SekreterIslemleri();
    /**
     * Creates new form HemsireEkrani
     */
    DefaultTableModel model;
    public static int receteNo;
    public SekreterEkrani() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        this.setLocation(x, y);
        model = (DefaultTableModel) HastaTablosu.getModel();
        sonucGoruntule();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AltPanel = new javax.swing.JPanel();
        UstPanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        EkranAdi = new javax.swing.JLabel();
        KapamaTusu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HastaTablosu = new javax.swing.JTable();
        HastalarYazisi = new javax.swing.JLabel();
        HastaAraYazisi = new javax.swing.JLabel();
        AramaAlani = new javax.swing.JTextField();
        İlacAdlariYazisi = new javax.swing.JLabel();
        IlacAlani = new javax.swing.JTextField();
        YazdirTusu = new javax.swing.JButton();
        Adyazisi = new javax.swing.JLabel();
        AdAlani = new javax.swing.JTextField();
        Soyadyazisi = new javax.swing.JLabel();
        SoyadAlani = new javax.swing.JTextField();
        TcAlani = new javax.swing.JTextField();
        tcYazisi = new javax.swing.JLabel();
        Ekle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        AltPanel.setBackground(new java.awt.Color(0, 0, 153));

        UstPanel.setBackground(new java.awt.Color(0, 102, 204));

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\HastaneOtomasyonu\\src\\com\\hastaneotomasyonu\\images\\icons8-hospital-3-64.png")); // NOI18N

        EkranAdi.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        EkranAdi.setForeground(new java.awt.Color(153, 255, 255));
        EkranAdi.setText("SEKRETER EKRANI");

        KapamaTusu.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\HastaneOtomasyonu\\src\\com\\hastaneotomasyonu\\images\\icons8-close-32.png")); // NOI18N
        KapamaTusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KapamaTusuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UstPanelLayout = new javax.swing.GroupLayout(UstPanel);
        UstPanel.setLayout(UstPanelLayout);
        UstPanelLayout.setHorizontalGroup(
            UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addComponent(Logo)
                .addGap(18, 18, 18)
                .addComponent(EkranAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KapamaTusu))
        );
        UstPanelLayout.setVerticalGroup(
            UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(EkranAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addComponent(KapamaTusu)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        HastaTablosu.setBackground(new java.awt.Color(0, 102, 204));
        HastaTablosu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        HastaTablosu.setForeground(new java.awt.Color(0, 0, 153));
        HastaTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "T.C. KİMLİK NO", "AD SOYAD", "İLAÇLAR"
            }
        ));
        HastaTablosu.setSelectionBackground(new java.awt.Color(0, 102, 204));
        HastaTablosu.setSelectionForeground(new java.awt.Color(0, 0, 153));
        HastaTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HastaTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(HastaTablosu);

        HastalarYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        HastalarYazisi.setForeground(new java.awt.Color(153, 255, 255));
        HastalarYazisi.setText("HASTALAR:");

        HastaAraYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        HastaAraYazisi.setForeground(new java.awt.Color(153, 255, 255));
        HastaAraYazisi.setText("HASTA ARA:");

        AramaAlani.setBackground(new java.awt.Color(0, 102, 204));
        AramaAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        AramaAlani.setForeground(new java.awt.Color(0, 0, 153));
        AramaAlani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AramaAlaniKeyReleased(evt);
            }
        });

        İlacAdlariYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        İlacAdlariYazisi.setForeground(new java.awt.Color(153, 255, 255));
        İlacAdlariYazisi.setText("İLAÇ ADLARI:");

        IlacAlani.setBackground(new java.awt.Color(0, 102, 204));
        IlacAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        IlacAlani.setForeground(new java.awt.Color(0, 0, 153));

        YazdirTusu.setBackground(new java.awt.Color(0, 102, 204));
        YazdirTusu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        YazdirTusu.setForeground(new java.awt.Color(0, 0, 153));
        YazdirTusu.setText("YAZDIR");
        YazdirTusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YazdirTusuActionPerformed(evt);
            }
        });

        Adyazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        Adyazisi.setForeground(new java.awt.Color(153, 255, 255));
        Adyazisi.setText("Ad:");

        AdAlani.setBackground(new java.awt.Color(0, 102, 204));
        AdAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        AdAlani.setForeground(new java.awt.Color(0, 0, 153));

        Soyadyazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        Soyadyazisi.setForeground(new java.awt.Color(153, 255, 255));
        Soyadyazisi.setText("Soyad:");

        SoyadAlani.setBackground(new java.awt.Color(0, 102, 204));
        SoyadAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        SoyadAlani.setForeground(new java.awt.Color(0, 0, 153));

        TcAlani.setBackground(new java.awt.Color(0, 102, 204));
        TcAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        TcAlani.setForeground(new java.awt.Color(0, 0, 153));
        TcAlani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TcAlaniKeyTyped(evt);
            }
        });

        tcYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        tcYazisi.setForeground(new java.awt.Color(153, 255, 255));
        tcYazisi.setText("T.C.");

        Ekle.setBackground(new java.awt.Color(0, 102, 204));
        Ekle.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        Ekle.setForeground(new java.awt.Color(0, 0, 153));
        Ekle.setText("EKLE");
        Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AltPanelLayout = new javax.swing.GroupLayout(AltPanel);
        AltPanel.setLayout(AltPanelLayout);
        AltPanelLayout.setHorizontalGroup(
            AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AltPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AltPanelLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(Adyazisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(Soyadyazisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SoyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tcYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TcAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(AltPanelLayout.createSequentialGroup()
                        .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AltPanelLayout.createSequentialGroup()
                                .addComponent(HastalarYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205)
                                .addComponent(HastaAraYazisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AramaAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AltPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(İlacAdlariYazisi)
                                .addGap(18, 18, 18)
                                .addComponent(IlacAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(YazdirTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
        );
        AltPanelLayout.setVerticalGroup(
            AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltPanelLayout.createSequentialGroup()
                .addComponent(UstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HastaAraYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AramaAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HastalarYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IlacAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(İlacAdlariYazisi)
                        .addComponent(YazdirTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Soyadyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TcAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AltPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AltPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
      public void sonucGoruntule() {
        model.setRowCount(0);
        ArrayList<Rect> sonuc = new ArrayList<>();
        sonuc = sekreterIslemleri.receteGoster();
        if (sonuc != null) {
            for (Rect sonc : sonuc) {
                int no = sonc.getNo();
                String tc = sonc.getTc();
                String adSoyad = sonc.getAd() + " " + sonc.getSoyad();
                String ilac = sonc.getIlacAd();
           
                
                Object[] ekleme = {tc, adSoyad, ilac};
                
                model.addRow(ekleme);
                
            }
        }
        
    }
    private void YazdirTusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YazdirTusuActionPerformed
         if (IlacAlani.getText().equals("")) {
        } else {
            
            String tc = TcAlani.getText();
            String ilac = IlacAlani.getText();
            
            sekreterIslemleri.guncelle(tc, ilac);
            sonucGoruntule();
        }
    }//GEN-LAST:event_YazdirTusuActionPerformed

    private void KapamaTusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KapamaTusuMouseClicked
       System.exit(0);
    }//GEN-LAST:event_KapamaTusuMouseClicked

    private void HastaTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HastaTablosuMouseClicked
        int selectedRow = HastaTablosu.getSelectedRow();
        
        String tc = model.getValueAt(selectedRow, 0).toString();
        TcAlani.setText(tc);
        String adSoyad = model.getValueAt(selectedRow, 1).toString();
        String[] dizi = adSoyad.split(" ");
        String ad;
        String soyad;
        switch (dizi.length) {
            case 4:
                ad = dizi[0] + " " + dizi[1];
                soyad = dizi[2] + " " + dizi[3];
                break;
            case 3:
                ad = dizi[0] + " " + dizi[1];
                soyad = dizi[2];
                break;
            default:
                ad = dizi[0];
                soyad = dizi[1];
                break;
        }
        AdAlani.setText(ad);
        SoyadAlani.setText(soyad);
        String ilac = model.getValueAt(selectedRow, 2).toString();
        IlacAlani.setText(ilac);
        

    }//GEN-LAST:event_HastaTablosuMouseClicked
     private void dinamikAra(String ara) {
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>(model);

        HastaTablosu.setRowSorter(rowSorter);

        rowSorter.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void AramaAlaniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AramaAlaniKeyReleased
         String ara = AramaAlani.getText();

         dinamikAra(ara);
    }//GEN-LAST:event_AramaAlaniKeyReleased

    private void TcAlaniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TcAlaniKeyTyped
        char c = evt.getKeyChar();
        if (TcAlani.getText().length() >= 11 || (c == KeyEvent.VK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TcAlaniKeyTyped

    private void EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EkleActionPerformed
        String tc = TcAlani.getText();
        String ad = AdAlani.getText();
        String soyad = SoyadAlani.getText();
        String ilac = IlacAlani.getText();
        if (TcAlani.equals("") || AdAlani.equals("") || SoyadAlani.equals("") || IlacAlani.equals("")) {
            JOptionPane.showMessageDialog(this, "Bilgileri eksiksiz giriniz!!!");
        } else {
            int no = sekreterIslemleri.noOlustur();

            sekreterIslemleri.receteYaz(no, ad, soyad, ilac, tc);
            sonucGoruntule();
            receteNo = no;
        }
    }//GEN-LAST:event_EkleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SekreterEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SekreterEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SekreterEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SekreterEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SekreterEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdAlani;
    private javax.swing.JLabel Adyazisi;
    private javax.swing.JPanel AltPanel;
    private javax.swing.JTextField AramaAlani;
    private javax.swing.JButton Ekle;
    private javax.swing.JLabel EkranAdi;
    private javax.swing.JLabel HastaAraYazisi;
    private javax.swing.JTable HastaTablosu;
    private javax.swing.JLabel HastalarYazisi;
    private javax.swing.JTextField IlacAlani;
    private javax.swing.JLabel KapamaTusu;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField SoyadAlani;
    private javax.swing.JLabel Soyadyazisi;
    private javax.swing.JTextField TcAlani;
    private javax.swing.JPanel UstPanel;
    private javax.swing.JButton YazdirTusu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tcYazisi;
    private javax.swing.JLabel İlacAdlariYazisi;
    // End of variables declaration//GEN-END:variables
}
