/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hastaneotomasyonu.danisma;

import com.hastaneotomasyonu.veritabani.VeritabaniIslemleri;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USER
 */
public class DanismaEkrani extends javax.swing.JFrame {

    VeritabaniIslemleri veritabaniIslemleri = new VeritabaniIslemleri();
    DanismaIslemleri danismaIslemleri = new DanismaIslemleri();

    /**
     * Creates new form DanismaEkrani
     */
    DefaultTableModel model;

    public DanismaEkrani() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        this.setLocation(x, y);
        model = (DefaultTableModel) RandevuTablosu.getModel();
        randevuGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AltPanel = new javax.swing.JPanel();
        UstPanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        EkranAdi = new javax.swing.JLabel();
        KapamaTusu = new javax.swing.JLabel();
        RandevuYazisi = new javax.swing.JLabel();
        HastaKayitTusu = new javax.swing.JButton();
        RandevuAlimiTusu = new javax.swing.JButton();
        SonucEkraniTusu = new javax.swing.JButton();
        RandevuAramaAlani = new javax.swing.JTextField();
        RandevuAraYazisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RandevuTablosu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AltPanel.setBackground(new java.awt.Color(0, 0, 153));

        UstPanel.setBackground(new java.awt.Color(0, 102, 204));

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\HastaneOtomasyonu\\src\\com\\hastaneotomasyonu\\images\\icons8-hospital-3-64.png")); // NOI18N

        EkranAdi.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        EkranAdi.setForeground(new java.awt.Color(153, 255, 255));
        EkranAdi.setText("DANIŞMAN EKRANI");

        KapamaTusu.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\HastaneOtomasyonu\\src\\com\\hastaneotomasyonu\\images\\icons8-close-32.png")); // NOI18N
        KapamaTusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KapamaTusuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UstPanelLayout = new javax.swing.GroupLayout(UstPanel);
        UstPanel.setLayout(UstPanelLayout);
        UstPanelLayout.setHorizontalGroup(
            UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addComponent(Logo)
                .addGap(18, 18, 18)
                .addComponent(EkranAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(KapamaTusu))
        );
        UstPanelLayout.setVerticalGroup(
            UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EkranAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addComponent(KapamaTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        RandevuYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        RandevuYazisi.setForeground(new java.awt.Color(153, 255, 255));
        RandevuYazisi.setText("ALINAN RANDEVULAR:");

        HastaKayitTusu.setBackground(new java.awt.Color(0, 102, 204));
        HastaKayitTusu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        HastaKayitTusu.setForeground(new java.awt.Color(0, 0, 153));
        HastaKayitTusu.setText("Hasta Kayıt");
        HastaKayitTusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HastaKayitTusuActionPerformed(evt);
            }
        });

        RandevuAlimiTusu.setBackground(new java.awt.Color(0, 102, 204));
        RandevuAlimiTusu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        RandevuAlimiTusu.setForeground(new java.awt.Color(0, 0, 153));
        RandevuAlimiTusu.setText("Randevu Alımı");
        RandevuAlimiTusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandevuAlimiTusuActionPerformed(evt);
            }
        });

        SonucEkraniTusu.setBackground(new java.awt.Color(0, 102, 204));
        SonucEkraniTusu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        SonucEkraniTusu.setForeground(new java.awt.Color(0, 0, 153));
        SonucEkraniTusu.setText("Sonuç Ekranı");
        SonucEkraniTusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SonucEkraniTusuActionPerformed(evt);
            }
        });

        RandevuAramaAlani.setBackground(new java.awt.Color(0, 102, 204));
        RandevuAramaAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        RandevuAramaAlani.setForeground(new java.awt.Color(0, 0, 153));
        RandevuAramaAlani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RandevuAramaAlaniKeyReleased(evt);
            }
        });

        RandevuAraYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        RandevuAraYazisi.setForeground(new java.awt.Color(153, 255, 255));
        RandevuAraYazisi.setText("Randevu Ara:");

        RandevuTablosu.setBackground(new java.awt.Color(0, 102, 204));
        RandevuTablosu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        RandevuTablosu.setForeground(new java.awt.Color(0, 0, 153));
        RandevuTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TC KİMLİK NO", "HASTA  AD SOYAD", "KLİNİK AD", "DOKTOR AD SOYAD", "TARİH", "SAAT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RandevuTablosu.setSelectionBackground(new java.awt.Color(0, 102, 204));
        RandevuTablosu.setSelectionForeground(new java.awt.Color(0, 0, 153));
        jScrollPane1.setViewportView(RandevuTablosu);

        javax.swing.GroupLayout AltPanelLayout = new javax.swing.GroupLayout(AltPanel);
        AltPanel.setLayout(AltPanelLayout);
        AltPanelLayout.setHorizontalGroup(
            AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AltPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RandevuYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(RandevuAraYazisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RandevuAramaAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AltPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SonucEkraniTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RandevuAlimiTusu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HastaKayitTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(jScrollPane1)
        );
        AltPanelLayout.setVerticalGroup(
            AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltPanelLayout.createSequentialGroup()
                .addComponent(UstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RandevuYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RandevuAramaAlani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RandevuAraYazisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SonucEkraniTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RandevuAlimiTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HastaKayitTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(AltPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KapamaTusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KapamaTusuMouseClicked
        System.exit(0);
    }//GEN-LAST:event_KapamaTusuMouseClicked

    private void SonucEkraniTusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SonucEkraniTusuActionPerformed
        SonucEkrani sonucEkrani = new SonucEkrani();
        sonucEkrani.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_SonucEkraniTusuActionPerformed

    private void RandevuAlimiTusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandevuAlimiTusuActionPerformed
        RandevuAlimi randevuAlimi = new RandevuAlimi();
        randevuAlimi.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_RandevuAlimiTusuActionPerformed

    private void HastaKayitTusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HastaKayitTusuActionPerformed
        HastaKayitEkrani hastaKayitEkrani = new HastaKayitEkrani();
        hastaKayitEkrani.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_HastaKayitTusuActionPerformed
    public void dinamikAra(String ara) {
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>(model);
        RandevuTablosu.setRowSorter(rowSorter);
        rowSorter.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void RandevuAramaAlaniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RandevuAramaAlaniKeyReleased
        String ara = RandevuAramaAlani.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_RandevuAramaAlaniKeyReleased
    public void randevuGoruntule() {
        model.setRowCount(0);

        ArrayList<Randevu> randevu = new ArrayList<>();

        randevu = danismaIslemleri.randevuGoster();

        if (randevu != null) {
            for (Randevu rand : randevu) {
                int no = rand.getId();
                String tc = rand.getTc();
                String adsoyad = rand.getAd() + " " + rand.getSoyad();
                String brans = rand.getBrans();
                String doktorAdSoyad = rand.getDoktorAdi();
                String tarih = rand.getTarih();
                String saat = rand.getSaat();

                Object[] ekleme = {tc, adsoyad, brans, doktorAdSoyad, tarih, saat};
                model.addRow(ekleme);

            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanismaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanismaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanismaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanismaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanismaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AltPanel;
    private javax.swing.JLabel EkranAdi;
    private javax.swing.JButton HastaKayitTusu;
    private javax.swing.JLabel KapamaTusu;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton RandevuAlimiTusu;
    private javax.swing.JLabel RandevuAraYazisi;
    private javax.swing.JTextField RandevuAramaAlani;
    private javax.swing.JTable RandevuTablosu;
    private javax.swing.JLabel RandevuYazisi;
    private javax.swing.JButton SonucEkraniTusu;
    private javax.swing.JPanel UstPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
