/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hastaneotomasyonu.danisma;

import com.hastaneotomasyonu.veritabani.VeritabaniIslemleri;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class HastaKayitEkrani extends javax.swing.JFrame {
     VeritabaniIslemleri veritabaniIslemleri = new VeritabaniIslemleri();
     DanismaIslemleri danismaIslemleri = new DanismaIslemleri();
     public static int hastaNo;
    /**
     * Creates new form HastaKayitEkrani
     */
    public HastaKayitEkrani() {
        initComponents();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AltPanel = new javax.swing.JPanel();
        UstPanel = new javax.swing.JPanel();
        EkranAdi = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        KapamaTusu = new javax.swing.JLabel();
        TCAlani = new javax.swing.JTextField();
        AdAlani = new javax.swing.JTextField();
        SoyadAlani = new javax.swing.JTextField();
        TelefonAlani = new javax.swing.JTextField();
        CinsiyetAlani = new javax.swing.JTextField();
        KaydetTusu = new javax.swing.JButton();
        TCyazisi = new javax.swing.JLabel();
        AdYazisi = new javax.swing.JLabel();
        SoyadYazisi = new javax.swing.JLabel();
        TelefonYazisi = new javax.swing.JLabel();
        CinsiyetYazisi = new javax.swing.JLabel();
        BransAlani = new javax.swing.JComboBox<>();
        BransYazisi = new javax.swing.JLabel();
        DoktorYazis = new javax.swing.JLabel();
        DoktorAdiAlani = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        AltPanel.setBackground(new java.awt.Color(0, 0, 153));

        UstPanel.setBackground(new java.awt.Color(0, 102, 204));

        EkranAdi.setFont(new java.awt.Font("Segoe Script", 1, 24)); // NOI18N
        EkranAdi.setForeground(new java.awt.Color(153, 255, 255));
        EkranAdi.setText("Hasta Kayıt");

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\HastaneOtomasyonu\\src\\com\\hastaneotomasyonu\\images\\icons8-hospital-3-64.png")); // NOI18N

        KapamaTusu.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\HastaneOtomasyonu\\src\\com\\hastaneotomasyonu\\images\\icons8-close-32.png")); // NOI18N
        KapamaTusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KapamaTusuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UstPanelLayout = new javax.swing.GroupLayout(UstPanel);
        UstPanel.setLayout(UstPanelLayout);
        UstPanelLayout.setHorizontalGroup(
            UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addComponent(Logo)
                .addGap(18, 18, 18)
                .addComponent(EkranAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(KapamaTusu))
        );
        UstPanelLayout.setVerticalGroup(
            UstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addComponent(KapamaTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(UstPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(EkranAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        TCAlani.setBackground(new java.awt.Color(0, 102, 204));
        TCAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        TCAlani.setForeground(new java.awt.Color(0, 0, 153));
        TCAlani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TCAlaniKeyTyped(evt);
            }
        });

        AdAlani.setBackground(new java.awt.Color(0, 102, 204));
        AdAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        AdAlani.setForeground(new java.awt.Color(0, 0, 153));

        SoyadAlani.setBackground(new java.awt.Color(0, 102, 204));
        SoyadAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        SoyadAlani.setForeground(new java.awt.Color(0, 0, 153));

        TelefonAlani.setBackground(new java.awt.Color(0, 102, 204));
        TelefonAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        TelefonAlani.setForeground(new java.awt.Color(0, 0, 153));

        CinsiyetAlani.setBackground(new java.awt.Color(0, 102, 204));
        CinsiyetAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        CinsiyetAlani.setForeground(new java.awt.Color(0, 0, 153));
        CinsiyetAlani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CinsiyetAlaniKeyTyped(evt);
            }
        });

        KaydetTusu.setBackground(new java.awt.Color(0, 102, 204));
        KaydetTusu.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        KaydetTusu.setForeground(new java.awt.Color(0, 0, 153));
        KaydetTusu.setText("Kaydet");
        KaydetTusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaydetTusuActionPerformed(evt);
            }
        });

        TCyazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        TCyazisi.setForeground(new java.awt.Color(153, 255, 255));
        TCyazisi.setText("T.C:");

        AdYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        AdYazisi.setForeground(new java.awt.Color(153, 255, 255));
        AdYazisi.setText("AD:");

        SoyadYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        SoyadYazisi.setForeground(new java.awt.Color(153, 255, 255));
        SoyadYazisi.setText("SOYAD:");

        TelefonYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        TelefonYazisi.setForeground(new java.awt.Color(153, 255, 255));
        TelefonYazisi.setText("TELEFON NO:");

        CinsiyetYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        CinsiyetYazisi.setForeground(new java.awt.Color(153, 255, 255));
        CinsiyetYazisi.setText("CİNSİYET:");

        BransAlani.setBackground(new java.awt.Color(0, 102, 204));
        BransAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        BransAlani.setForeground(new java.awt.Color(0, 0, 153));
        BransAlani.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Meme Cerrahisi", "Dermatoloji", "Psikiyatri", "Göz Hastalıkları", "Estetik, Plastik ve Rekonstrüktif Cerrahisi", "Kalp ve Damar Cerrahisi", "Endokrinoloji ve Metabolizma Hastalıkları", "Radyoloji", "Romatoloji", "Fizik Tedavi ve Rehabilitasyon", "Kadın Hastalıkları ve Doğum", "Kardiyoloji", "Nefroloji", "Genel Cerrah", "Dahiliye (İç Hastalıkları)", "Üroloji", "Gastroenteroloji", "Göğüs Hastalıkları", "Nöroloji", "Hematoloji", "Çocuk Sağlığı ve Hastalıkları", " ", " " }));

        BransYazisi.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        BransYazisi.setForeground(new java.awt.Color(153, 255, 255));
        BransYazisi.setText("BRANŞ:");

        DoktorYazis.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        DoktorYazis.setForeground(new java.awt.Color(153, 255, 255));
        DoktorYazis.setText("DOKTOR ADI:");

        DoktorAdiAlani.setBackground(new java.awt.Color(0, 102, 204));
        DoktorAdiAlani.setFont(new java.awt.Font("Segoe Script", 1, 12)); // NOI18N
        DoktorAdiAlani.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout AltPanelLayout = new javax.swing.GroupLayout(AltPanel);
        AltPanel.setLayout(AltPanelLayout);
        AltPanelLayout.setHorizontalGroup(
            AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UstPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AltPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(KaydetTusu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(AltPanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SoyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(AltPanelLayout.createSequentialGroup()
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DoktorYazis)
                    .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AltPanelLayout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AdYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SoyadYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TCyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AltPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CinsiyetYazisi, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TelefonYazisi, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BransYazisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TelefonAlani)
                    .addComponent(CinsiyetAlani)
                    .addComponent(BransAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoktorAdiAlani))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AltPanelLayout.setVerticalGroup(
            AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AltPanelLayout.createSequentialGroup()
                .addComponent(UstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdYazisi)
                    .addComponent(AdAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoyadYazisi)
                    .addComponent(SoyadAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoktorYazis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoktorAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BransYazisi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BransAlani, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefonYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AltPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CinsiyetAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CinsiyetYazisi))
                .addGap(18, 18, 18)
                .addComponent(KaydetTusu)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AltPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AltPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KapamaTusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KapamaTusuMouseClicked
        DanismaEkrani danismaEkrani = new DanismaEkrani();
        danismaEkrani.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_KapamaTusuMouseClicked

    private void KaydetTusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaydetTusuActionPerformed
         String tc = TCAlani.getText();
         String ad = AdAlani.getText();
         String soyad = SoyadAlani.getText();
         String doktor = DoktorAdiAlani.getText();
         int klinikNo = danismaIslemleri.klinikNoSec(BransAlani.getSelectedIndex());
         String brans = danismaIslemleri.klinikAdiBul(klinikNo);
         String telefon = TelefonAlani.getText();
         String cinsiyet = CinsiyetAlani.getText();

        if (TCAlani.equals("") || AdAlani.equals("") || SoyadAlani.equals("") || DoktorAdiAlani.equals("") || BransAlani.equals("")
                || TelefonAlani.equals("") || CinsiyetAlani.equals("")) {
            JOptionPane.showMessageDialog(this, "Bilgileri eksiksiz giriniz!!!");
        } else {
            int no = danismaIslemleri.noOlustur();

            danismaIslemleri.kayitYap(no, ad, soyad, tc, doktor, brans, telefon, cinsiyet);

            hastaNo = no;

            JOptionPane.showMessageDialog(this, "Kayıt Başarıyla gerçekleşti :)");
        }
    }//GEN-LAST:event_KaydetTusuActionPerformed

    private void TCAlaniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCAlaniKeyTyped
       char c = evt.getKeyChar();
        if (TCAlani.getText().length() >= 11 || (c == KeyEvent.VK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_TCAlaniKeyTyped

    private void CinsiyetAlaniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CinsiyetAlaniKeyTyped
           char c = evt.getKeyChar();
        if (CinsiyetAlani.getText().length() >= 5 || (c == KeyEvent.VK_SPACE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_CinsiyetAlaniKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HastaKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HastaKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HastaKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HastaKayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HastaKayitEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdAlani;
    private javax.swing.JLabel AdYazisi;
    private javax.swing.JPanel AltPanel;
    private javax.swing.JComboBox<String> BransAlani;
    private javax.swing.JLabel BransYazisi;
    private javax.swing.JTextField CinsiyetAlani;
    private javax.swing.JLabel CinsiyetYazisi;
    private javax.swing.JTextField DoktorAdiAlani;
    private javax.swing.JLabel DoktorYazis;
    private javax.swing.JLabel EkranAdi;
    private javax.swing.JLabel KapamaTusu;
    private javax.swing.JButton KaydetTusu;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField SoyadAlani;
    private javax.swing.JLabel SoyadYazisi;
    private javax.swing.JTextField TCAlani;
    private javax.swing.JLabel TCyazisi;
    private javax.swing.JTextField TelefonAlani;
    private javax.swing.JLabel TelefonYazisi;
    private javax.swing.JPanel UstPanel;
    // End of variables declaration//GEN-END:variables
}
